export const constants = {
	stage: {
		width: 800,
		height: 600,
		bulletMargin: 100,
	},
	player: {
		width: 50,
		height: 60,
		speed: 2.5,
		rotationSpeed: 1,
		minRotation: -5,
		maxRotation: 5,
		swingAmplitudeY: 4,
		swingFrequencyY: 0.0025,
		frictionFactor: 0.05,
		accelerationFactor: 0.05,
	},
	frames: {
		player: [
			'/player/1.png',
			'/player/2.png',
			'/player/3.png',
			'/player/4.png',
			'/player/5.png',
			'/player/6.png',
			'/player/7.png',
			'/player/8.png',
			'/player/9.png',
			'/player/10.png',
			'/player/11.png',
			'/player/12.png',
			'/player/13.png',
		],
	},
};
